### PR TITLE
Added support for m4v

### PR DESCRIPTION
**Pull request by emredalka**
Ver 1.7.1 not find my file with mp4 extension. When I look at signature I recognize that is video/x-m4v file.
Mp4 BYTE_INFO was too general. I edited Mp4 BYTE_INFO according to "https://www.garykessler.net/library/file_sigs.html" and added file signature for m4v.

### CODE REVIEW

**Comment by SidOfc** [comment]
Hello, thank you for your contribution! I will check this out and add a test for m4v files.
Also thank you for adding this brilliant resource, I'll add it to the list of [credits and other resources](https://github.com/SidOfc/leather#credits-and-other-resources-that-saved-my-soul) section :)

**Comment by SidOfc** [comment]
When I converted my `test/files/example.mp4` to a `m4v` file using `ffmpeg -i test/files/example.mp4 test/files/example.m4v` the test I wrote for it failed. When I checked your link I noticed 2 m4v sequences:

- `66 74 79 70 6D 70 34 32` (`ftypmp42`)
- `66 74 79 70 4D 34 56 20` (`ftypm4v`)

The latter `ftypm4v` one was what `ffmpeg` created by default and seems to be correct as well.
I already made some changes to the code to patch this, add a test, and replace the `switch` statement with something a bit less verbose (all good though, I'm not anti-switch but this seemed like a perfect candidate for a lookup-table)

**Comment by emredalka** [comment]
Hello Sidney,

Why were you removed  '667479706d703432': 'video/x-m4v'
from src/extractors/mp4.js file? Are there any issue with it?
https://github.com/SidOfc/leather/commit/5344696c61509e820a12e76c7741da001587ffed#diff-b15d9a5e497ca05638ce11d2a9dcda3aacfd8d1a8f264c8166fdcd40f7d4e52a

*Emre DALKA*
***@***.*** ***@***.***>*
*(553) 424 78 78*


Sidney Liebrand ***@***.***>, 4 Eyl 2022 Paz, 15:51 tarihinde
şunu yazdı:

**Comment by SidOfc** [comment]
@emredalka I added some context in my last comment before your reply, did you read this?

**Pull request merged**
